# Generated by Django 6.0.2 on 2026-02-05 21:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Dooars Prajukti', help_text='Company name', max_length=200)),
                ('tagline', models.CharField(blank=True, help_text='Company tagline or slogan', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Company description for about page')),
                ('founded_year', models.IntegerField(blank=True, help_text='Year company was founded (for calculating years of experience)', null=True, validators=[django.core.validators.MinValueValidator(1900)])),
                ('email', models.EmailField(blank=True, help_text='Primary company email', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Primary phone number', max_length=20)),
                ('address_line1', models.CharField(blank=True, help_text='Street address', max_length=255)),
                ('address_line2', models.CharField(blank=True, help_text='Additional address details', max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('business_hours', models.CharField(blank=True, default='Mon - Sat: 9:00 AM - 6:00 PM', help_text='Business hours text', max_length=200)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('meta_description', models.TextField(blank=True, help_text='Default meta description for SEO (max 160 characters)', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords for SEO', max_length=255)),
                ('hero_title', models.CharField(blank=True, help_text='Main hero section title on homepage', max_length=200)),
                ('hero_subtitle', models.TextField(blank=True, help_text='Hero section subtitle/description', max_length=500)),
                ('hero_cta_text', models.CharField(blank=True, default='Get Started', help_text='Call-to-action button text', max_length=50)),
                ('hero_cta_link', models.CharField(blank=True, default='/contact/', help_text='Call-to-action button link', max_length=200)),
                ('manual_years_experience', models.IntegerField(blank=True, help_text='Manually set years of experience (overrides auto-calculation)', null=True)),
                ('footer_text', models.TextField(blank=True, default='Building innovative digital solutions for businesses worldwide.', help_text='Footer description text', max_length=500)),
                ('copyright_text', models.CharField(blank=True, help_text='Copyright text (leave blank to auto-generate)', max_length=200)),
                ('logo', models.ImageField(blank=True, help_text='Company logo', null=True, upload_to='company/')),
                ('favicon', models.ImageField(blank=True, help_text='Website favicon', null=True, upload_to='company/')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Enable to show maintenance page')),
                ('maintenance_message', models.TextField(blank=True, help_text='Message to display during maintenance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Settings',
                'verbose_name_plural': 'Company Settings',
            },
        ),
    ]
